// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHKom92segDj1vXM5l-DoelsI8AW2-8DE',
    appId: '1:217372431910:web:servikoWebPlaceholder',
    messagingSenderId: '217372431910',
    projectId: 'serviko-yaml',
    authDomain: 'serviko-yaml.firebaseapp.com',
    storageBucket: 'serviko-yaml.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHKom92segDj1vXM5l-DoelsI8AW2-8DE',
    appId: '1:217372431910:android:a1b08b02cb6c38ebb878e7',
    messagingSenderId: '217372431910',
    projectId: 'serviko-yaml',
    storageBucket: 'serviko-yaml.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHKom92segDj1vXM5l-DoelsI8AW2-8DE',
    appId: '1:217372431910:ios:servikoIosPlaceholder',
    messagingSenderId: '217372431910',
    projectId: 'serviko-yaml',
    storageBucket: 'serviko-yaml.firebasestorage.app',
    iosBundleId: 'com.example.flutter_application_1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHKom92segDj1vXM5l-DoelsI8AW2-8DE',
    appId: '1:217372431910:ios:servikoIosPlaceholder',
    messagingSenderId: '217372431910',
    projectId: 'serviko-yaml',
    storageBucket: 'serviko-yaml.firebasestorage.app',
    iosBundleId: 'com.example.flutter_application_1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCHKom92segDj1vXM5l-DoelsI8AW2-8DE',
    appId: '1:217372431910:web:servikoWindowsPlaceholder',
    messagingSenderId: '217372431910',
    projectId: 'serviko-yaml',
    authDomain: 'serviko-yaml.firebaseapp.com',
    storageBucket: 'serviko-yaml.firebasestorage.app',
  );
}
